language: python

python:
  - 2.7
  - 3.3

cache: pip

install:
  - pip install coveralls
  - pip install coverage
  - pip install flask

env:
  CODECLIMATE_REPO_TOKEN: b3e484cc63dd28cbecbad3d97cb600952bc68eb235dc89687e99cba4d0ac0dcd

script:
  - nosetests --with-coverage --cover-package=app

after_success: coveralls

